// <auto-generated />
using System;
using Ascend_Forum.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ascend_Forum.Infrastructure.Migrations
{
    [DbContext(typeof(AscendForumDbContext))]
    [Migration("20260329144405_SeedingDB")]
    partial class SeedingDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Latest trends in technology and software development.",
                            ImageUrl = "https://picsum.photos/id/1/200/300",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Discuss everything about video games and consoles.",
                            ImageUrl = "https://picsum.photos/id/2/200/300",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Space, Biology, Physics and more.",
                            ImageUrl = "https://picsum.photos/id/3/200/300",
                            Name = "Science"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Coding challenges, best practices and career advice.",
                            ImageUrl = "https://picsum.photos/id/4/200/300",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Health, travel and general discussion.",
                            ImageUrl = "https://picsum.photos/id/5/200/300",
                            Name = "Lifestyle"
                        });
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Comment 1 for post 1. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Comment 2 for post 1. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Comment 1 for post 2. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 2
                        },
                        new
                        {
                            Id = 4,
                            Content = "Comment 2 for post 2. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Comment 1 for post 3. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "Comment 2 for post 3. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "Comment 1 for post 4. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 4
                        },
                        new
                        {
                            Id = 8,
                            Content = "Comment 2 for post 4. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 4
                        },
                        new
                        {
                            Id = 9,
                            Content = "Comment 1 for post 5. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 5
                        },
                        new
                        {
                            Id = 10,
                            Content = "Comment 2 for post 5. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 5
                        },
                        new
                        {
                            Id = 11,
                            Content = "Comment 1 for post 6. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 6
                        },
                        new
                        {
                            Id = 12,
                            Content = "Comment 2 for post 6. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 6
                        },
                        new
                        {
                            Id = 13,
                            Content = "Comment 1 for post 7. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 7
                        },
                        new
                        {
                            Id = 14,
                            Content = "Comment 2 for post 7. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 7
                        },
                        new
                        {
                            Id = 15,
                            Content = "Comment 1 for post 8. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 8
                        },
                        new
                        {
                            Id = 16,
                            Content = "Comment 2 for post 8. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 8
                        },
                        new
                        {
                            Id = 17,
                            Content = "Comment 1 for post 9. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 9
                        },
                        new
                        {
                            Id = 18,
                            Content = "Comment 2 for post 9. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 9
                        },
                        new
                        {
                            Id = 19,
                            Content = "Comment 1 for post 10. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 10
                        },
                        new
                        {
                            Id = 20,
                            Content = "Comment 2 for post 10. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 10
                        },
                        new
                        {
                            Id = 21,
                            Content = "Comment 1 for post 11. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 11
                        },
                        new
                        {
                            Id = 22,
                            Content = "Comment 2 for post 11. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 11
                        },
                        new
                        {
                            Id = 23,
                            Content = "Comment 1 for post 12. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 12
                        },
                        new
                        {
                            Id = 24,
                            Content = "Comment 2 for post 12. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 12
                        },
                        new
                        {
                            Id = 25,
                            Content = "Comment 1 for post 13. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 13
                        },
                        new
                        {
                            Id = 26,
                            Content = "Comment 2 for post 13. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 13
                        },
                        new
                        {
                            Id = 27,
                            Content = "Comment 1 for post 14. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 14
                        },
                        new
                        {
                            Id = 28,
                            Content = "Comment 2 for post 14. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 14
                        },
                        new
                        {
                            Id = 29,
                            Content = "Comment 1 for post 15. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 15
                        },
                        new
                        {
                            Id = 30,
                            Content = "Comment 2 for post 15. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 15
                        },
                        new
                        {
                            Id = 31,
                            Content = "Comment 1 for post 16. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 16
                        },
                        new
                        {
                            Id = 32,
                            Content = "Comment 2 for post 16. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 16
                        },
                        new
                        {
                            Id = 33,
                            Content = "Comment 1 for post 17. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 17
                        },
                        new
                        {
                            Id = 34,
                            Content = "Comment 2 for post 17. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 17
                        },
                        new
                        {
                            Id = 35,
                            Content = "Comment 1 for post 18. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 18
                        },
                        new
                        {
                            Id = 36,
                            Content = "Comment 2 for post 18. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 18
                        },
                        new
                        {
                            Id = 37,
                            Content = "Comment 1 for post 19. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 19
                        },
                        new
                        {
                            Id = 38,
                            Content = "Comment 2 for post 19. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 19
                        },
                        new
                        {
                            Id = 39,
                            Content = "Comment 1 for post 20. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 20
                        },
                        new
                        {
                            Id = 40,
                            Content = "Comment 2 for post 20. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 20
                        },
                        new
                        {
                            Id = 41,
                            Content = "Comment 1 for post 21. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 21
                        },
                        new
                        {
                            Id = 42,
                            Content = "Comment 2 for post 21. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 21
                        },
                        new
                        {
                            Id = 43,
                            Content = "Comment 1 for post 22. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 22
                        },
                        new
                        {
                            Id = 44,
                            Content = "Comment 2 for post 22. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 22
                        },
                        new
                        {
                            Id = 45,
                            Content = "Comment 1 for post 23. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 23
                        },
                        new
                        {
                            Id = 46,
                            Content = "Comment 2 for post 23. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            PostId = 23
                        },
                        new
                        {
                            Id = 47,
                            Content = "Comment 1 for post 24. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            PostId = 24
                        },
                        new
                        {
                            Id = 48,
                            Content = "Comment 2 for post 24. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            PostId = 24
                        },
                        new
                        {
                            Id = 49,
                            Content = "Comment 1 for post 25. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            PostId = 25
                        },
                        new
                        {
                            Id = 50,
                            Content = "Comment 2 for post 25. Nice post!",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            PostId = 25
                        });
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique();

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 1,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 2,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 3,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 4,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 5,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 6,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 7,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 8,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 9,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 10,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 11,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 12,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 13,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 14,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 15,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 16,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 17,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 18,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 19,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 20,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 21,
                            CommentId = 21,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 22,
                            CommentId = 22,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 23,
                            CommentId = 23,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 24,
                            CommentId = 24,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 25,
                            CommentId = 25,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 26,
                            CommentId = 26,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 27,
                            CommentId = 27,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 28,
                            CommentId = 28,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 29,
                            CommentId = 29,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 30,
                            CommentId = 30,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 31,
                            CommentId = 31,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 32,
                            CommentId = 32,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 33,
                            CommentId = 33,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 34,
                            CommentId = 34,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 35,
                            CommentId = 35,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 36,
                            CommentId = 36,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 37,
                            CommentId = 37,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 38,
                            CommentId = 38,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 39,
                            CommentId = 39,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 40,
                            CommentId = 40,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 41,
                            CommentId = 41,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 42,
                            CommentId = 42,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 43,
                            CommentId = 43,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 44,
                            CommentId = 44,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 45,
                            CommentId = 45,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user1-id-guid"
                        },
                        new
                        {
                            Id = 46,
                            CommentId = 46,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user2-id-guid"
                        },
                        new
                        {
                            Id = 47,
                            CommentId = 47,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user3-id-guid"
                        },
                        new
                        {
                            Id = 48,
                            CommentId = 48,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user4-id-guid"
                        },
                        new
                        {
                            Id = 49,
                            CommentId = 49,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 2,
                            UserId = "user5-id-guid"
                        },
                        new
                        {
                            Id = 50,
                            CommentId = 50,
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            ReactionType = 1,
                            UserId = "user1-id-guid"
                        });
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "This is the content for post 1 in category 1. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            Title = "Post 1 in Category 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Content = "This is the content for post 2 in category 1. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            Title = "Post 2 in Category 1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Content = "This is the content for post 3 in category 1. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            Title = "Post 3 in Category 1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Content = "This is the content for post 4 in category 1. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            Title = "Post 4 in Category 1"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Content = "This is the content for post 5 in category 1. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            Title = "Post 5 in Category 1"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Content = "This is the content for post 1 in category 2. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            Title = "Post 1 in Category 2"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Content = "This is the content for post 2 in category 2. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            Title = "Post 2 in Category 2"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Content = "This is the content for post 3 in category 2. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            Title = "Post 3 in Category 2"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Content = "This is the content for post 4 in category 2. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            Title = "Post 4 in Category 2"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Content = "This is the content for post 5 in category 2. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            Title = "Post 5 in Category 2"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Content = "This is the content for post 1 in category 3. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            Title = "Post 1 in Category 3"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Content = "This is the content for post 2 in category 3. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            Title = "Post 2 in Category 3"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Content = "This is the content for post 3 in category 3. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            Title = "Post 3 in Category 3"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Content = "This is the content for post 4 in category 3. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            Title = "Post 4 in Category 3"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Content = "This is the content for post 5 in category 3. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            Title = "Post 5 in Category 3"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            Content = "This is the content for post 1 in category 4. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            Title = "Post 1 in Category 4"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Content = "This is the content for post 2 in category 4. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            Title = "Post 2 in Category 4"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Content = "This is the content for post 3 in category 4. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            Title = "Post 3 in Category 4"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Content = "This is the content for post 4 in category 4. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            Title = "Post 4 in Category 4"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Content = "This is the content for post 5 in category 4. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            Title = "Post 5 in Category 4"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Content = "This is the content for post 1 in category 5. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user1-id-guid",
                            Title = "Post 1 in Category 5"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Content = "This is the content for post 2 in category 5. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user2-id-guid",
                            Title = "Post 2 in Category 5"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Content = "This is the content for post 3 in category 5. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user3-id-guid",
                            Title = "Post 3 in Category 5"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Content = "This is the content for post 4 in category 5. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user4-id-guid",
                            Title = "Post 4 in Category 5"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Content = "This is the content for post 5 in category 5. It contains some useful information.",
                            CreatedOn = new DateTime(2026, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = "user5-id-guid",
                            Title = "Post 5 in Category 5"
                        });
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AscendName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AscendName")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user1-id-guid",
                            AccessFailedCount = 0,
                            AscendName = "JohnD",
                            ConcurrencyStamp = "32f7a925-a319-4b11-a57c-3249afa12826",
                            Email = "john@example.com",
                            EmailConfirmed = false,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN@EXAMPLE.COM",
                            NormalizedUserName = "JOHN_DOE",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bfc71631-94dc-4e96-a1f5-a8c2a873e76b",
                            TwoFactorEnabled = false,
                            UserName = "john_doe"
                        },
                        new
                        {
                            Id = "user2-id-guid",
                            AccessFailedCount = 0,
                            AscendName = "JaneS",
                            ConcurrencyStamp = "837a16f2-e19f-42fb-8e2c-c88c95b6e3bd",
                            Email = "jane@example.com",
                            EmailConfirmed = false,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE@EXAMPLE.COM",
                            NormalizedUserName = "JANE_SMITH",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a9a9e9e1-1c77-4045-beba-4a17bc172051",
                            TwoFactorEnabled = false,
                            UserName = "jane_smith"
                        },
                        new
                        {
                            Id = "user3-id-guid",
                            AccessFailedCount = 0,
                            AscendName = "BobB",
                            ConcurrencyStamp = "afc3f667-5c62-44fc-9dea-fe421ef547b3",
                            Email = "bob@example.com",
                            EmailConfirmed = false,
                            FirstName = "Bob",
                            LastName = "Builder",
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB@EXAMPLE.COM",
                            NormalizedUserName = "BOB_BUILDER",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "553fb997-9c9b-4019-a567-f696ceb59244",
                            TwoFactorEnabled = false,
                            UserName = "bob_builder"
                        },
                        new
                        {
                            Id = "user4-id-guid",
                            AccessFailedCount = 0,
                            AscendName = "AliceW",
                            ConcurrencyStamp = "be68dcd3-adcd-489c-8654-a49e56c7b2e4",
                            Email = "alice@example.com",
                            EmailConfirmed = false,
                            FirstName = "Alice",
                            LastName = "Wonder",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE@EXAMPLE.COM",
                            NormalizedUserName = "ALICE_WONDER",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76927ff1-c7c3-465e-8377-aaadbe1a947d",
                            TwoFactorEnabled = false,
                            UserName = "alice_wonder"
                        },
                        new
                        {
                            Id = "user5-id-guid",
                            AccessFailedCount = 0,
                            AscendName = "CharlieB",
                            ConcurrencyStamp = "dc2e087c-0ae5-4027-80ad-35cd817fe2ad",
                            Email = "charlie@example.com",
                            EmailConfirmed = false,
                            FirstName = "Charlie",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHARLIE@EXAMPLE.COM",
                            NormalizedUserName = "CHARLIE_BROWN",
                            PasswordHash = "AQAAAAEAACcQAAAAE...",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b2654e37-220f-4fc3-8987-085a93850d9f",
                            TwoFactorEnabled = false,
                            UserName = "charlie_brown"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.Comment", b =>
                {
                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.User", "Creator")
                        .WithMany("Comments")
                        .HasForeignKey("CreatorId");

                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.Comment", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Parent");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.CommentReaction", b =>
                {
                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.User", "User")
                        .WithMany("CommentReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.Post", b =>
                {
                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.User", "Creator")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ascend_Forum.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Ascend_Forum.Infrastructure.Data.Models.User", b =>
                {
                    b.Navigation("CommentReactions");

                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
